FROM golang:1.23-alpine
RUN go install github.com/pressly/goose/v3/cmd/goose@latest
WORKDIR /storage/sql/migrations
COPY storage/sql/migrations/*.sql ./
ENTRYPOINT ["goose", "postgres", "host=postgres port=5432 user=dev password=dev dbname=lms sslmode=disable", "up"]
